#!/bin/ruby

require 'i3rb'

i3bar = I3::Bar.get_instance do |bar|
  bar.hostname.color = "#00FFFF"
  bar.hostname.add_event_callback do |w,e|
    if e.button == 1
      cmd = 'i3-sensible-terminal -e top'
      ret = system cmd
      $stderr.puts "#{cmd} => #{ret}"
    end
  end
  bar.add_basic_widgets
end

i3bar.start_events_capturing
i3bar.add_event_callback do |w,e|
  $stderr.puts "Widget #{w} catched event #{e}"
end
i3bar.run 1
