#!/bin/ruby

require 'i3rb'
require 'thor'
require 'pry'

$debug = true

class I3::CLI < Thor

  include I3::API

  desc "pry", "Start pry session within i3 ipc connection"
  def pry
    binding.pry
  end

end

I3::CLI.start ARGV
